# Chapter 7

## 7.1 Handling Missing Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avacado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avacado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [9]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [11]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [14]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = np.nan

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [23]:
df.iloc[:4, 1] = np.nan

In [24]:
df.iloc[:2, 2] = np.nan

In [25]:
df

0         1         2
0  1.586491       NaN       NaN
1 -0.679391       NaN       NaN
2  0.423533       NaN  0.123378
3  1.232789       NaN  1.851205
4  0.357386 -0.009946  0.929300
5  0.314714 -2.487444  0.931348
6 -1.739221 -0.217556 -0.618476

In [26]:
df.dropna()

0         1         2
4  0.357386 -0.009946  0.929300
5  0.314714 -2.487444  0.931348
6 -1.739221 -0.217556 -0.618476

In [27]:
df.dropna(thresh=2)

0         1         2
2  0.423533       NaN  0.123378
3  1.232789       NaN  1.851205
4  0.357386 -0.009946  0.929300
5  0.314714 -2.487444  0.931348
6 -1.739221 -0.217556 -0.618476

### Filling in Missing Data

In [28]:
df.fillna(0)

0         1         2
0  1.586491  0.000000  0.000000
1 -0.679391  0.000000  0.000000
2  0.423533  0.000000  0.123378
3  1.232789  0.000000  1.851205
4  0.357386 -0.009946  0.929300
5  0.314714 -2.487444  0.931348
6 -1.739221 -0.217556 -0.618476

In [29]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  1.586491  0.500000  0.000000
1 -0.679391  0.500000  0.000000
2  0.423533  0.500000  0.123378
3  1.232789  0.500000  1.851205
4  0.357386 -0.009946  0.929300
5  0.314714 -2.487444  0.931348
6 -1.739221 -0.217556 -0.618476

In [30]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [31]:
df.iloc[2:, 1] = np.nan

In [32]:
df.iloc[4: 2] = np.nan

In [33]:
df

0         1         2
0  0.129276 -0.394426  0.671747
1  0.815297 -0.562843  1.791655
2 -1.583063       NaN -0.614773
3 -0.976340       NaN -0.388214
4  1.865820       NaN -0.147824
5  1.265440       NaN -1.892107

In [34]:
df.fillna(method="ffill")

0         1         2
0  0.129276 -0.394426  0.671747
1  0.815297 -0.562843  1.791655
2 -1.583063 -0.562843 -0.614773
3 -0.976340 -0.562843 -0.388214
4  1.865820 -0.562843 -0.147824
5  1.265440 -0.562843 -1.892107

In [35]:
df.fillna(method="ffill", limit=2)

0         1         2
0  0.129276 -0.394426  0.671747
1  0.815297 -0.562843  1.791655
2 -1.583063 -0.562843 -0.614773
3 -0.976340 -0.562843 -0.388214
4  1.865820       NaN -0.147824
5  1.265440       NaN -1.892107

In [36]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Data Transfromation

### Removing Duplicates

In [38]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4 ]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data["v1"] = range(7)

In [43]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [46]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                             "pastrami", "corned beef", "bacon",
                             "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [49]:
data["animal"] = data["food"].map(meat_to_animal)

In [50]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [51]:
def get_animal(x):
    return meat_to_animal[x]

In [52]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [54]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [57]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [58]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=["Ohio", "Colorado", "New York"],
                   columns=["one", "two", "three", "four"])

In [59]:
def transform(x):
    return x[:4].upper()

In [60]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [61]:
data.index = data.index.map(transform)

In [62]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [63]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [64]:
data.rename(index={"OHIO": "INDIANA"},
           columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and Binning

In [65]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [66]:
bins = [18, 25, 35, 60, 100]

In [67]:
age_categories = pd.cut(ages, bins)

In [68]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [69]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [70]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [71]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [72]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [73]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [74]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [75]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [76]:
data = np.random.uniform(size=20)

In [77]:
pd.cut(data, 4, precision=2)

[(0.26, 0.48], (0.48, 0.7], (0.48, 0.7], (0.7, 0.92], (0.26, 0.48], ..., (0.26, 0.48], (0.48, 0.7], (0.7, 0.92], (0.7, 0.92], (0.044, 0.26]]
Length: 20
Categories (4, interval[float64, right]): [(0.044, 0.26] < (0.26, 0.48] < (0.48, 0.7] < (0.7, 0.92]]

In [78]:
data = np.random.standard_normal(1000)

In [79]:
quartiles = pd.qcut(data, 4, precision=2)

In [80]:
quartiles

[(0.61, 2.92], (-3.8699999999999997, -0.67], (0.61, 2.92], (-0.67, -0.0091], (-0.0091, 0.61], ..., (0.61, 2.92], (-0.67, -0.0091], (-3.8699999999999997, -0.67], (0.61, 2.92], (-0.67, -0.0091]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.8699999999999997, -0.67] < (-0.67, -0.0091] < (-0.0091, 0.61] < (0.61, 2.92]]

In [81]:
pd.value_counts(quartiles)

(-3.8699999999999997, -0.67]    250
(-0.67, -0.0091]                250
(-0.0091, 0.61]                 250
(0.61, 2.92]                    250
dtype: int64

In [82]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.862, -1.24]      100
(-1.24, -0.00914]    400
(-0.00914, 1.226]    400
(1.226, 2.919]       100
dtype: int64

In [83]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-0.00914, 1.226], (-3.862, -1.24], (1.226, 2.919], (-1.24, -0.00914], (-0.00914, 1.226], ..., (-0.00914, 1.226], (-1.24, -0.00914], (-3.862, -1.24], (-0.00914, 1.226], (-1.24, -0.00914]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.862, -1.24] < (-1.24, -0.00914] < (-0.00914, 1.226] < (1.226, 2.919]]

### Detecting and Filtering Outliers

In [84]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [85]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.007932    -0.007792    -0.014435    -0.003090
std       1.005615     0.990067     1.013901     0.988640
min      -3.219257    -3.071940    -3.785934    -2.895548
25%      -0.640285    -0.660746    -0.647719    -0.657452
50%       0.000194     0.011091    -0.003154    -0.004265
75%       0.674081     0.671271     0.652809     0.671030
max       3.288767     3.055868     2.879656     3.287636

In [86]:
col = data[2]

In [87]:
col[col.abs() > 3]

432   -3.447870
478   -3.194045
775   -3.027789
976   -3.785934
Name: 2, dtype: float64

In [88]:
col

0      0.053160
1      0.367252
2      1.218893
3      0.445482
4      1.007045
         ...   
995    1.359921
996    0.428867
997    0.187548
998    0.177692
999    0.142417
Name: 2, Length: 1000, dtype: float64

In [89]:
data.head()

0         1         2         3
0  0.378207  0.331062  0.053160  1.738570
1 -0.209531  1.281508  0.367252 -0.063379
2  0.968157  1.839477  1.218893 -0.286715
3 -0.571323  2.100584  0.445482  2.235438
4 -0.244874 -0.957818  1.007045 -0.877839

In [90]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
293 -0.566198 -3.071940 -0.275007 -1.157065
357  3.288767  0.188290  0.553932 -0.593862
432  0.753127  0.227595 -3.447870  1.376886
478  1.909895  0.699772 -3.194045 -0.661356
645  3.246724  1.412432 -0.729370 -0.907251
654 -1.063323 -3.004721 -0.022118 -0.184028
744 -0.774145  3.055868 -0.362748 -0.496648
775 -1.239697  0.069732 -3.027789 -0.988376
795  3.121059 -0.828851  1.490537 -0.480456
836 -3.219257  1.421367 -1.890818 -0.173943
838 -0.455464  0.627596  1.235756  3.287636
925 -3.017151  1.269196 -0.575012  0.772281
976  0.019601  0.421007 -3.785934 -0.652455

In [91]:
data[data.abs() < 3] = np.sign(data) * 3

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.000420     0.041979    -0.007456    -0.011712
std       3.002429     3.001341     3.003091     3.001780
min      -3.219257    -3.071940    -3.785934    -3.000000
25%      -3.000000    -3.000000    -3.000000    -3.000000
50%       0.000000     3.000000    -3.000000    -3.000000
75%       3.000000     3.000000     3.000000     3.000000
max       3.288767     3.055868     3.000000     3.287636

In [93]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1 -1.0  1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0  1.0  1.0  1.0
4 -1.0 -1.0  1.0 -1.0

### Permutation and Random Sampling

In [94]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [95]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [96]:
sampler = np.random.permutation(5)

In [97]:
sampler

array([1, 2, 0, 4, 3])

In [98]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [99]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [100]:
column_sampler = np.random.permutation(7)

In [101]:
column_sampler

array([1, 5, 2, 0, 4, 6, 3])

In [102]:
df.take(column_sampler, axis="columns")

1   5   2   0   4   6   3
0   1   5   2   0   4   6   3
1   8  12   9   7  11  13  10
2  15  19  16  14  18  20  17
3  22  26  23  21  25  27  24
4  29  33  30  28  32  34  31

In [103]:
df.sample(n=3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [104]:
choices = pd.Series([5, 7, -1, 6, 4])

In [105]:
choices.sample(n=10, replace=True)

0    5
2   -1
2   -1
2   -1
4    4
2   -1
3    6
0    5
0    5
0    5
dtype: int64

### Computing Indicator/Dummy Variables

In [106]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [107]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [108]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [109]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [110]:
df_with_dummy = df[["data1"]].join(dummies)

In [111]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [112]:
mnames = ["movie_id", "title", "genres"]

In [113]:
movies = pd.read_table(r"C:\Users\seanb\Desktop\Pyhon_for_Data_Analysis\Ch7\datasets\movielens\movies.dat", sep="::", header=None,
                      names=mnames, engine="python")

In [114]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [115]:
dummies = movies["genres"].str.get_dummies("|")

In [116]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [117]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [118]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [119]:
np.random.seed(12345) # To make the example repeatable

In [120]:
values = np.random.uniform(size=10)

In [121]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [122]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [123]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 Extension Data Types

In [124]:
s = pd.Series([1, 2, 3, None])

In [125]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [126]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [127]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [128]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [129]:
s.dtype

Int64Dtype()

In [130]:
s[3]

<NA>

In [131]:
s[3] is pd.NA

True

In [132]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [133]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [134]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [135]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                  "B": ["one", "two", "three", None],
                  "C": [False, None, False, True]})

In [136]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [137]:
df["A"] = df["A"].astype("Int64")

In [138]:
df["B"] = df["B"].astype("string")

In [139]:
df["C"] = df["C"].astype("boolean")

In [140]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## 7.4 String Manipulation

### Python Built-In String Object Methods

In [141]:
val = "a, b,  guido"

In [142]:
val.split(",")

['a', ' b', '  guido']

In [143]:
pieces = [x.strip() for x in val.split(",")]

In [144]:
pieces

['a', 'b', 'guido']

In [145]:
first, second, third = pieces

In [146]:
first + "::" + second + "::" + third

'a::b::guido'

In [147]:
"::".join(pieces)

'a::b::guido'

In [148]:
"guido" in val

True

In [149]:
val.index(",")

1

In [150]:
val.find(":")

-1

In [151]:
val.count(",")

2

In [152]:
val.replace(",", "::")

'a:: b::  guido'

In [153]:
val.replace(",", "")

'a b  guido'

### Regular Expressions

In [154]:
import re

In [155]:
text = "foo    bar\t baz  \tquz"

In [156]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'quz']

In [157]:
regex = re.compile(r"\s+")

In [158]:
regex.split(text)

['foo', 'bar', 'baz', 'quz']

In [162]:
regex.findall(text)

[]

In [171]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [172]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [173]:
m = regex.search(text)

In [174]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [175]:
text[m.start():m.end()]

'dave@google.com'

In [176]:
print(regex.match(text))

None


In [177]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [182]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [183]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [184]:
m = regex.match('wesm@bright.net')

In [185]:
m.groups()

('wesm', 'bright', 'net')

In [186]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [187]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


### String Functions in pandas

In [188]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
       "Rob": "rob@gmail.com", "Wes": np.nan}

In [189]:
data = pd.Series(data)

In [190]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [191]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [192]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [193]:
data_as_string_ext = data.astype('string')

In [194]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [195]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [196]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [197]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [198]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [199]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [200]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [201]:
matches.str.get(2)

Dave     com
Steve    com
Rob      com
Wes      NaN
dtype: object

In [202]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [203]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

## 7.5 Categorical Data

### Background and Motivation

In [205]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [206]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [207]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [208]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [209]:
values = pd.Series([0, 1, 0, 0] * 2)

In [210]:
dim = pd.Series(['apple', 'orange'])

In [211]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [212]:
dim

0     apple
1    orange
dtype: object

In [213]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Categorical Extension Type in pandas

In [214]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [216]:
N = len(fruits)

In [217]:
rng = np.random.default_rng(seed=12345)

In [218]:
df = pd.DataFrame({'fruit': fruits,
                  'basket_id': np.arange(N),
                  'count': rng.integers(3, 15, size=N),
                  'weight': rng.uniform(0, 4, size=N)},
                 columns=['basket_id', 'fruit', 'count', 'weight'])

In [219]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [221]:
fruit_cat = df['fruit'].astype('category')

In [222]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [223]:
c = fruit_cat.array

In [224]:
type(c)

pandas.core.arrays.categorical.Categorical

In [225]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [226]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [227]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [228]:
df['fruit'] = df['fruit'].astype('category')

In [229]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [230]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [231]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [232]:
categories = ['foo', 'bar', 'baz']

In [233]:
codes = [0, 1, 2, 0, 0, 1]

In [234]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [235]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [236]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [238]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [239]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

### Computations with Categoricals

In [240]:
rng = np.random.default_rng(seed=12345)

In [241]:
draws = rng.standard_normal(1000)

In [242]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [243]:
bins = pd.qcut(draws, 4)

In [244]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [245]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [246]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [248]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [249]:
bins = pd.Series(bins, name='quartile')

In [250]:
results = (pd.Series(draws)
          .groupby(bins)
          .agg(['count', 'min', 'max'])
          .reset_index())

In [251]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [252]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

#### Better performance with categoricals

In [253]:
N = 10_000_000

In [254]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [255]:
categories = labels.astype('category')

In [257]:
labels.memory_usage(deep=True)

600000128

In [258]:
categories.memory_usage(deep=True)

10000540

In [259]:
%time _ = labels.astype('category')

Wall time: 1.03 s


In [262]:
%timeit labels.value_counts()

576 ms ± 22.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [263]:
%timeit categories.value_counts()

126 ms ± 6.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Categorical Methods

In [264]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [265]:
cat_s = s.astype('category')

In [266]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [267]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [268]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [269]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [270]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [271]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [273]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [274]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [276]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [277]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [278]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

#### Creating dummy variables for modeling

In [279]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [280]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1